# File: .github/workflows/workflow.yml

on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/ebfe7521-4254-44fe-a5d0-188778af3a26/resourceGroups/contoso-traders-rg1653404             
        scopes-ignore: |
          /subscriptions/ebfe7521-4254-44fe-a5d0-188778af3a26/resourceGroups/contoso-traders-rg1653404/providers/microsoft.authorization
     
